name: aust_textile_alumni
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: ^0.13.5
  get_storage: ^2.0.3
  flutter_svg:
  url_launcher: ^6.1.6
  toggle_switch: ^2.0.1
  outlined_text: ^1.0.1
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  file_picker: ^5.2.1
  sqflite: ^2.1.0+1
  path_provider: ^2.0.11
  flutter_quill: ^6.0.8+1
  delta_to_html: ^0.2.0
  lottie: ^1.4.1
  flutter_html: ^2.2.1
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  qr_code_scanner: ^1.0.0
  firebase_messaging: ^14.0.4
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  flutter_local_notifications:
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  dropdown_search: ^0.6.3
  intl_phone_number_input: ^0.7.1
  chewie: ^1.3.5
  video_player: ^2.4.7



  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/files/


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu.ttf
        - asset: assets/fonts/Poppins-Regular.ttf

